<a href="https://colab.research.google.com/github/giuliavalcu/ML-Seminar-ValcuGiulia/blob/main/LP1_Machine_Learning_in_Python_NOU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/cristinaboboc-1975/Seminar-Machine-learning-in-Python/blob/main/LP1_Machine_Learning_in_Python_NOU.ipynb)

# Laborator 1 — Bazele limbajului Python pentru Machine Learning

**Curs:** Machine Learning in Python · Laborator asociat Cursului 1 (Introducere în Machine Learning)

### Ce vei învăța în acest laborator
- Expresii, tipuri de date (numere, text) și operatori în Python
- Variabile, atribuiri și denumirea corectă a acestora
- Comparații și valori booleene
- Apelarea funcțiilor și a funcțiilor din librării (`math`, `operator`)
- Vectori (`numpy`), liste și indexare
- Crearea și manipularea tabelelor de date cu `pandas` (DataFrame)
- Citirea unui fișier CSV real și o primă curățare a datelor

> 💡 **Recomandare:** nu doar citi celulele — rulează-le, modifică-le și experimentează. Exersarea activă este esențială pentru a înțelege sintaxa Python.

In [1]:
# Când deschideți acest notebook, rulați mai întâi celula de mai jos pentru a importa
# librăriile de bază de care veți avea nevoie pe tot parcursul laboratorului.

# Librării de bază
import pandas as pd
import numpy as np

## 1. Expresii

### Noțiuni preliminare

Despre limbajul de programare Python:
- este popular atât pentru *data science*, cât și pentru dezvoltarea de aplicații software;
- stăpânirea noțiunilor de bază ale limbajului este extrem de importantă;
- sintaxa de bază este ușor de înțeles;
- este esențială **exersarea** metodelor și procedurilor — nu doar citirea codului sau ascultarea explicațiilor.

In [2]:
3 * 4

12

In [3]:
3 * 4 + 5 * 3

27

Expresiile în Python respectă aceleași reguli de precedență ca în algebră: înmulțirea și împărțirea au prioritate față de adunare și scădere. Parantezele pot fi folosite pentru a grupa expresii mai mici într-o expresie mai mare.

In [4]:
# Parantezele sunt folosite pentru a grupa subexpresiile
3 * (4 + 5) * 3

81

In [5]:
2 ** 5   # ridicare la putere: 2 la puterea 5

32

⚠️ **Atenție la sintaxă.** Limbajele de programare sunt foarte pretențioase în privința sintaxei — un singur spațiu sau simbol greșit produce o eroare. Celula de mai jos conține **intenționat** o eroare de sintaxă (`* *` în loc de `**`), pentru a vedea cum arată un mesaj de eroare în Python.

In [6]:
# Această celulă va genera o eroare (SyntaxError) — este intenționat!
2 * * 5

SyntaxError: invalid syntax (1945756881.py, line 2)

## 2. Tipuri de date: numere

Numerele întregi se numesc valori **int** în Python. Ele reprezintă doar numere întregi (negative, zero sau pozitive), fără componentă fracționară.

Numerele reale se numesc valori **float** (*floating point*). Ele pot reprezenta atât numere întregi, cât și fracționare, dar au unele limitări:
- au o dimensiune limitată (deși limita este foarte mare);
- au o precizie limitată la aproximativ 15 cifre semnificative.

In [7]:
# Împărțire (rezultatul este întotdeauna float)
9 / 2

4.5

In [8]:
# Tipul rezultatului
type(9 / 2)

float

In [9]:
# Împărțirea întreagă (câtul împărțirii)
9 // 2

4

In [10]:
# Ce tip are rezultatul împărțirii întregi?
type(9 // 2)

int

In [11]:
int(4.5)   # trunchiază partea zecimală

4

In [12]:
int('4.5')   # ❗ nu funcționează direct pe un șir cu zecimale — vom vedea eroarea

ValueError: invalid literal for int() with base 10: '4.5'

## 3. Atribuiri și nume

- Instrucțiunile nu au o valoare; ele efectuează o acțiune.
- O instrucțiune de **atribuire** schimbă semnificația numelui din stânga simbolului `=`.
- Numele este legat de o **valoare** (nu de o formulă/ecuație — valoarea se calculează o singură dată, în momentul atribuirii).

In [13]:
num_1 = 5
num_2 = 20
# rezultatul înmulțirii, fără a-l atribui unei variabile
num_1 * num_2

100

In [14]:
# atribuirea rezultatului unei variabile
total = num_1 * num_2

In [15]:
print(total)

100


In [16]:
print(total * 2)

200


O serie de linii de cod, într-o singură celulă sau în celule succesive, permite construirea unui calcul complex în etape, dând nume rezultatelor intermediare — la fel ca mai jos.

In [17]:
total   # variabila 'total' rămâne disponibilă în celulele următoare

100

In [18]:
salariu_zilnic = 524
salariu_lunar = 20 * salariu_zilnic
numar_zile_lucratoare_an = 252
salariu_anual = numar_zile_lucratoare_an * salariu_zilnic
salariu_anual

132048

### 📝 Exercițiu

Atribuiți variabilei `numar_secunde_deceniu` numărul de secunde dintre miezul nopții de la 1 ianuarie 2010 și miezul nopții de la 1 ianuarie 2020 (un deceniu întreg, cu 2 ani bisecți: 2012 și 2016).

In [19]:
# Soluție — încearcă mai întâi singur/singură, apoi compară cu varianta de mai jos!
nr_ani_bisecti = 2
nr_secunde_minut = 60
nr_secunde_ora = nr_secunde_minut * 60
nr_secunde_zi = nr_secunde_ora * 24

numar_secunde_deceniu = (nr_ani_bisecti * nr_secunde_zi * 366
                          + 8 * nr_secunde_zi * 365)

numar_secunde_deceniu

315532800

## 4. Tipuri de date: text și șiruri de caractere

Un șir de caractere (**string**) este o porțiune de text de orice lungime:

- `'a'`
- `'cuvânt'`
- `"Noi suntem studenți!"`

Șirurile de caractere care conțin numere pot fi convertite în numere:
- `int('12')`
- `float('1.2')`

Orice valoare poate fi convertită într-un șir de caractere folosind `str(...)`, de exemplu `str(5)`.

In [20]:
str(5)

'5'

In [21]:
"Master " + "data" + " " + "science"   # concatenare de șiruri cu +

'Master data science'

In [22]:
# Atribuim variabile de tip text
d = "data"
s = "science"
spatiu = " "

In [23]:
d

'data'

In [24]:
# Folosim valorile din celula anterioară
d + spatiu + s

'data science'

In [25]:
str(2 ** 5)

'32'

In [26]:
suta = 100
print("Am " + str(suta) + " lei")   # 'str()' este necesar pentru a concatena un număr cu text

Am 100 lei


In [27]:
datasci = "data science"
polsci = datasci.replace("data", "political")
print(polsci)

political science


### 📝 Exercițiu — erori de tip (type errors)

Rulați, pe rând, fiecare dintre următoarele expresii, folosind:

```python
x = 3
y = '4'
z = '5.6'
```

- `x + y`
- `x + int(y + z)`
- `str(x) + int(y)`
- `str(x, y) + z`

Pentru fiecare, identificați **de ce** apare eroarea (sau, dacă nu apare, ce rezultat se obține).

In [28]:
x = 3
y = '4'
z = '5.6'

x + y   # ❗ TypeError: nu poți aduna direct un int (x) cu un str (y)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Explicații:**

- `x + y` → **eroare**: `x` este `int`, `y` este `str`; Python nu adună automat tipuri diferite.
- `x + int(y + z)` → **eroare**: `y + z` concatenează șirurile la `'45.6'`, iar `int('45.6')` eșuează pentru că șirul conține un punct zecimal (`int()` nu acceptă zecimale).
- `str(x) + int(y)` → **eroare**: `str(x)` este `'3'` (text), iar `int(y)` este `4` (număr); nu poți concatena text cu un număr folosind `+`.
- `str(x, y) + z` → **eroare**: `str()` nu acceptă doi parametri de acest fel — sintaxa este greșită.

Încearcă variantele corecte, de exemplu: `str(x) + y` sau `x + int(y)`.

## 5. Comparații și relații booleene

In [29]:
3 > 1 + 10

False

In [30]:
# Comparație înlănțuită — echivalentă cu (1 > 1+1) and (1+1 < 3)
1 > 1 + 1 < 3

False

In [31]:
x = 12
y = 50.0

# La ce se referă această operație? (indiciu: comparație înlănțuită)
min(x, y) <= (x + y) / 2 > max(x, y)

False

In [32]:
# Comparații ale unor șiruri de caractere, în ordine alfabetică
"Dog" > "Catastrophe" > "Horse"

False

In [33]:
# Literele mari sunt "mai mici" decât literele mici, în codificarea ASCII/Unicode
"D" < "d"

True

## 6. Apelarea unei funcții

Apelarea unei funcții este numită și **operație**. Numele funcției apare primul, urmat de argumente scrise între paranteze.

In [34]:
abs(-12)

12

In [35]:
round(5 - 1.3)

4

In [36]:
max(6, 4)

6

In [37]:
max(6, 4, 3 + 4)

7

In [38]:
# help() afișează documentația unei funcții
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more positional arguments, return the largest argument.



In [39]:
import math
import operator

print(math.ceil(3.2))
print(math.pi)
print(operator.pow(2, 5))
print(operator.add(2, 5))

4
3.141592653589793
32
7


## 7. Vectori, șiruri, tupluri și liste

Un **array** (vector, din `numpy`) conține o secvență de valori:

- toate elementele unui vector au, de regulă, același tip;
- operațiile aritmetice se aplică individual fiecărui element;
- când doi vectori sunt adunați, trebuie să aibă aceeași dimensiune — elementele corespunzătoare se adună între ele;
- o coloană dintr-un set de date este, în esență, un vector.

Un **range** (șir) este un vector de numere consecutive:
- `np.arange(end)` — generează numerele de la 0 până la `end - 1`.

In [40]:
# crearea unui vector folosind funcția numpy arange
my_array = np.arange(2, 8)
my_array

array([2, 3, 4, 5, 6, 7])

In [41]:
# crearea unei liste — folosind paranteze pătrate
# spre deosebire de vectori, listele pot conține valori de tipuri diferite
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

In [42]:
my_list1 = [1, 2, 3, 4, 'c']
my_list1

[1, 2, 3, 4, 'c']

In [43]:
print(sum(my_array))
print(my_array.sum())

27
27


⚠️ Următoarea celulă va genera o eroare: `sum()` nu poate aduna elemente de tipuri diferite (numere și text) dintr-o listă.

In [44]:
print(sum(my_list1))   # ❗ TypeError

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [45]:
print(sum(my_list))   # aici funcționează, toate elementele sunt numere

10


In [46]:
# adunarea a doi vectori — elementele corespunzătoare se adună
# (cei doi vectori trebuie să aibă aceeași dimensiune!)
my_array1 = np.arange(5, 11)
print(my_array1)
my_array + my_array1

[ 5  6  7  8  9 10]


array([ 7,  9, 11, 13, 15, 17])

In [47]:
print(my_array.size)
print(len(my_array))

6
6


In [48]:
np.count_nonzero([1, 2, 0, 2, 1, 0, 2])   # numără elementele diferite de 0

5

In [49]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [50]:
print(np.arange(5, 10, 2))   # start, stop, pas

[5 7 9]


In [51]:
venituri = np.array([500, 210, 300])
cheltuieli = np.array([400, 200, 280])
economii = venituri - cheltuieli
print("Economiile sunt " + str(economii))

Economiile sunt [100  10  20]


In [52]:
rata_economisire = economii / venituri
print("Rata de economisire este: " + str(np.round(rata_economisire, 2)))

Rata de economisire este: [0.2  0.05 0.07]


## 8. Extragerea elementelor dintr-un vector (indexare)

In [53]:
my_array3 = np.arange(101, 119)
# primul element din șir (indexarea începe de la 0!)
my_array3[0]

np.int64(101)

In [54]:
my_array3[1:7]   # elementele de la poziția 1 până la 6 (poziția 7 e exclusă)

array([102, 103, 104, 105, 106, 107])

In [55]:
# Care va fi rezultatul acestei expresii? Încearcă să prezici înainte de a rula.
my_array3[12:3:-2]   # start, stop, pas negativ (mergem invers)

array([113, 111, 109, 107, 105])

In [56]:
# Comanda split desparte un șir de caractere într-o listă de șiruri, după un separator dat
mystring1 = 'this is a long and dull exercise'
mystring1.split(' ')

['this', 'is', 'a', 'long', 'and', 'dull', 'exercise']

In [57]:
# Selectarea unui singur element din lista rezultată din split
mystring1.split(' ')[1]

'is'

### 📝 Exercițiu

Folosind comanda `split`, tăierea listei (*slicing*) și concatenarea șirurilor cu `+`, obțineți din șirul `'learning is done by machine'` rezultatul `'machine learning'`.

In [58]:
# Soluție — încearcă mai întâi singur/singură!
mach1 = 'learning is done by machine'
cuvinte = mach1.split(' ')       # ['learning', 'is', 'done', 'by', 'machine']
mach2 = cuvinte[-1] + ' ' + cuvinte[0]   # 'machine' + ' ' + 'learning'
mach2

'machine learning'

## 9. Crearea de tabele — DataFrame

In [59]:
# DataFrame() gol
pd.DataFrame()

""


In [60]:
pd.DataFrame({'Number of petals': [8, 34, 5]})

,Number of petals
0,8
1,34
2,5


In [61]:
# un DataFrame cu 2 coloane
pd.DataFrame({'Number of petals': [8, 34, 5],
              'Name': ['Lotus', 'Sunflower', 'Rose']})

,Number of petals,Name
0,8,Lotus
1,34,Sunflower
2,5,Rose


In [62]:
matrix = pd.DataFrame({'col1': [0, 4],
                        'col2': [1, 5],
                        'col3': [2, 6],
                        'col4': [3, 7]})
matrix

,col1,col2,col3,col4
0,0,1,2,3
1,4,5,6,7


In [63]:
matrix.T   # transpusa tabelului (rânduri <-> coloane)

,0,1
col1,0,4
col2,1,5
col3,2,6
col4,3,7


In [64]:
flowers = pd.DataFrame({'Number of petals': [8, 34, 5],
                         'Name': ['Lotus', 'Sunflower', 'Rose']})
flowers

,Number of petals,Name
0,8,Lotus
1,34,Sunflower
2,5,Rose


In [65]:
# adăugarea unei coloane noi
flowers = pd.DataFrame({'Number of petals': [8, 34, 5], 'Name': ['Lotus', 'Sunflower', 'Rose']})
flowers['Color'] = ['pink', 'yellow', 'red']
flowers

,Number of petals,Name,Color
0,8,Lotus,pink
1,34,Sunflower,yellow
2,5,Rose,red


In [66]:
flowers.shape   # (număr de rânduri, număr de coloane)

(3, 3)

In [67]:
# numărul de linii și numărul de coloane, separat
print(flowers.shape[0])
print(flowers.shape[1])
flowers

3
3


,Number of petals,Name,Color
0,8,Lotus,pink
1,34,Sunflower,yellow
2,5,Rose,red


In [68]:
flowers.columns.values   # numele coloanelor

array(['Number of petals', 'Name', 'Color'], dtype=object)

## 10. Citirea unui tabel de date într-un DataFrame

Tabelul `galton.csv` oferă date bazate pe faimosul studiu din 1885 al lui **Francis Galton**, care explorează relația dintre înălțimea copiilor adulți și înălțimea părinților lor. Fiecare caz este un copil adult, iar variabilele sunt:

- **family** — familia căreia îi aparține copilul, etichetată de la 1 la 205;
- **father** — înălțimea tatălui, în inci;
- **mother** — înălțimea mamei, în inci;
- **gender** — sexul copilului, bărbat (`male`) sau femeie (`female`);
- **childHeight** — înălțimea copilului.

**Încărcarea datelor** — celula de mai jos funcționează direct, oriunde ai rula notebook-ul (local, Jupyter, Colab), fără să fie nevoie de Google Drive: dacă ai deja fișierul `galton.csv` în același folder cu notebook-ul, îl citește de acolo; altfel îl descarcă automat de pe un depozit public (GitHub) și îl salvează local pentru rulările următoare.

In [69]:
import os

CSV_LOCAL = "galton.csv"
CSV_URL = "https://raw.githubusercontent.com/data-8/materials-fa17/master/lec/galton.csv"

if os.path.exists(CSV_LOCAL):
    galton_df = pd.read_csv(CSV_LOCAL)
else:
    galton_df = pd.read_csv(CSV_URL)
    galton_df.to_csv(CSV_LOCAL, index=False)   # salvăm local, pentru rulările următoare

galton_df.head()

,family,father,mother,midparentHeight,children,childNum,gender,childHeight
0,1,78.5,67.0,75.43,4,1,male,73.2
1,1,78.5,67.0,75.43,4,2,female,69.2
2,1,78.5,67.0,75.43,4,3,female,69.0
3,1,78.5,67.0,75.43,4,4,female,69.0
4,2,75.5,66.5,73.66,4,1,male,73.5


> 💡 **Notă pentru Google Colab:** dacă preferați să încărcați fișierul din propriul Google Drive (de exemplu, alt set de date pentru un proiect), puteți folosi codul de mai jos — **nu este necesar pentru `galton.csv`**, care se descarcă automat mai sus.
>
> ```python
> from google.colab import drive
> drive.mount('/content/drive')
> galton_df = pd.read_csv("/content/drive/MyDrive/<folderul_tau>/galton.csv")
> ```

In [70]:
galton_df.shape

(934, 8)

In [71]:
# selectarea primelor 8 rânduri — un mod de a extrage un subset de rânduri
galton_df.head(8)

,family,father,mother,midparentHeight,children,childNum,gender,childHeight
0,1,78.5,67.0,75.43,4,1,male,73.2
1,1,78.5,67.0,75.43,4,2,female,69.2
2,1,78.5,67.0,75.43,4,3,female,69.0
3,1,78.5,67.0,75.43,4,4,female,69.0
4,2,75.5,66.5,73.66,4,1,male,73.5
5,2,75.5,66.5,73.66,4,2,male,72.5
6,2,75.5,66.5,73.66,4,3,female,65.5
7,2,75.5,66.5,73.66,4,4,female,65.5


In [72]:
print('Coloanele și tipul datelor din Python:')
[(x, type(galton_df[x][0])) for x in galton_df.columns]

Coloanele și tipul datelor din Python:


[('family', str),
 ('father', numpy.float64),
 ('mother', numpy.float64),
 ('midparentHeight', numpy.float64),
 ('children', numpy.int64),
 ('childNum', numpy.int64),
 ('gender', str),
 ('childHeight', numpy.float64)]

In [73]:
galton_df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
family,934,205,185,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
father,934.0,NaN,NaN,NaN,69.197109,2.476479,62.0,68.0,69.0,71.0,78.5
mother,934.0,NaN,NaN,NaN,64.089293,2.290886,58.0,63.0,64.0,65.875,70.5
midparentHeight,934.0,NaN,NaN,NaN,69.206773,1.80237,64.4,68.14,69.248,70.14,75.43
children,934.0,NaN,NaN,NaN,6.171306,2.729025,1.0,4.0,6.0,8.0,15.0
childNum,934.0,NaN,NaN,NaN,3.585653,2.36141,1.0,2.0,3.0,5.0,15.0
gender,934,2,male,481,NaN,NaN,NaN,NaN,NaN,NaN,NaN
childHeight,934.0,NaN,NaN,NaN,66.745931,3.579251,56.0,64.0,66.5,69.7,79.0


## 11. Utilizarea DataFrame-urilor (Table)

In [74]:
# extragerea unei coloane
galton_df['gender'][0:10]

,gender
0,male
1,female
2,female
3,female
4,male
5,male
6,female
7,female
8,male
9,female


In [75]:
# un alt mod de a extrage o coloană (funcționează doar dacă numele nu conține spații)
galton_df.gender

,gender
0,male
1,female
2,female
3,female
4,male
...,...
929,male
930,female
931,female
932,male


In [76]:
type(galton_df[['gender', 'family']])

pandas.core.frame.DataFrame

In [77]:
# folosirea comenzii drop pentru a elimina o coloană nedorită
galton_df.drop(['children'], axis=1).head(10)

,family,father,mother,midparentHeight,childNum,gender,childHeight
0,1,78.5,67.0,75.43,1,male,73.2
1,1,78.5,67.0,75.43,2,female,69.2
2,1,78.5,67.0,75.43,3,female,69.0
3,1,78.5,67.0,75.43,4,female,69.0
4,2,75.5,66.5,73.66,1,male,73.5
5,2,75.5,66.5,73.66,2,male,72.5
6,2,75.5,66.5,73.66,3,female,65.5
7,2,75.5,66.5,73.66,4,female,65.5
8,3,75.0,64.0,72.06,1,male,71.0
9,3,75.0,64.0,72.06,2,female,68.0


In [78]:
new_df = galton_df[galton_df.midparentHeight > 75]

In [79]:
new_df

,family,father,mother,midparentHeight,children,childNum,gender,childHeight
0,1,78.5,67.0,75.43,4,1,male,73.2
1,1,78.5,67.0,75.43,4,2,female,69.2
2,1,78.5,67.0,75.43,4,3,female,69.0
3,1,78.5,67.0,75.43,4,4,female,69.0


In [80]:
# dacă vrem să selectăm anumite RÂNDURI, avem mai multe opțiuni
# iloc folosește poziția din tabel
galton_df.iloc[3:5]

,family,father,mother,midparentHeight,children,childNum,gender,childHeight
3,1,78.5,67.0,75.43,4,4,female,69.0
4,2,75.5,66.5,73.66,4,1,male,73.5


In [81]:
# extragerea observațiilor care verifică o anumită condiție (OR — cel puțin una din condiții)
galton_df[(galton_df.gender == 'female') | (galton_df.children == 4)]

,family,father,mother,midparentHeight,children,childNum,gender,childHeight
0,1,78.5,67.0,75.43,4,1,male,73.2
1,1,78.5,67.0,75.43,4,2,female,69.2
2,1,78.5,67.0,75.43,4,3,female,69.0
3,1,78.5,67.0,75.43,4,4,female,69.0
4,2,75.5,66.5,73.66,4,1,male,73.5
...,...,...,...,...,...,...,...,...
927,202,63.0,63.5,65.79,2,1,female,68.5
928,202,63.0,63.5,65.79,2,2,female,63.5
930,203,62.0,66.0,66.64,3,2,female,62.0
931,203,62.0,66.0,66.64,3,3,female,61.0


In [82]:
# extragerea observațiilor care verifică ambele condiții simultan (AND)
galton_df[(galton_df.gender == 'female') & (galton_df.children == 4)]

,family,father,mother,midparentHeight,children,childNum,gender,childHeight
1,1,78.5,67.0,75.43,4,2,female,69.2
2,1,78.5,67.0,75.43,4,3,female,69.0
3,1,78.5,67.0,75.43,4,4,female,69.0
6,2,75.5,66.5,73.66,4,3,female,65.5
7,2,75.5,66.5,73.66,4,4,female,65.5
135,36,71.0,67.0,71.68,4,4,female,67.0
137,37,71.0,66.0,71.14,4,2,female,67.0
138,37,71.0,66.0,71.14,4,3,female,67.0
139,37,71.0,66.0,71.14,4,4,female,66.5
178,47,71.7,64.5,70.68,4,4,female,67.0


In [83]:
# selectarea aleatoare a 5 rânduri
galton_df.sample(5)

,family,father,mother,midparentHeight,children,childNum,gender,childHeight
846,185,66.0,59.0,64.86,15,3,male,66.5
784,172,66.0,67.0,69.18,8,4,male,66.0
568,126,69.0,60.0,66.90,4,4,female,60.5
237,61,70.0,69.0,72.26,4,2,male,70.0
346,82,70.0,64.0,69.56,9,7,female,69.0


## 12. O primă curățare a datelor

Curățarea datelor este un pas important într-un proiect de machine learning — îl vom relua în detaliu în Cursurile 2 și 3.

In [84]:
# pentru fiecare coloană, numărăm valorile existente (nenule), ca să vedem
# cât de multe valori lipsă există în baza de date
galton_df.count()

,0
family,934
father,934
mother,934
midparentHeight,934
children,934
childNum,934
gender,934
childHeight,934


In [85]:
# înlăturarea coloanelor cu multe valori lipsă, sau păstrarea doar a coloanelor de interes
# în cazul nostru, păstrăm doar 3 coloane
galton3_df = galton_df[['father', 'mother', 'childHeight']]

# comanda pentru înlăturarea rândurilor cu valori lipsă (NaN)
galton3_df = galton3_df.dropna()
galton3_df.count()

,0
father,934
mother,934
childHeight,934


## Recapitulare

În acest laborator ai exersat:
- ✅ expresii, precedența operatorilor și tipurile de date de bază (`int`, `float`, `str`)
- ✅ atribuiri de variabile și denumirea corectă a acestora
- ✅ comparații și valori booleene
- ✅ apelarea funcțiilor, inclusiv din librăriile `math` și `operator`
- ✅ vectori (`numpy`) și liste — creare, operații, indexare
- ✅ tabele de date (`pandas` DataFrame) — creare, citire dintr-un CSV, selecție de rânduri/coloane
- ✅ o primă curățare a datelor (identificarea și eliminarea valorilor lipsă)

➡️ **Următorul laborator (LP 2)** continuă cu înțelegerea și pregătirea datelor: calitatea datelor, vizualizare, detectarea outlierilor și teste de normalitate — în pregătirea pentru primele modele de Machine Learning.